### PR TITLE
Adds first batch of pics

### PR DESCRIPTION
**Pull request by marimeireles**
Will probably cause some merging issues because I had to change the name of one of the pictures.

### CODE REVIEW

**Comment by marimeireles** [comment]
The plan for the  next PRs  is to wait for people to fill the content of the pages so I can  choose pics that relate to the text.

If you think I should just choose random pics, I can also  do that. Please let me know.

Thanks :)

**Comment by marimeireles** [comment]
@maartenbreddels

**Comment by SylvainCorlay** [comment]
@marimeireles thx. Inideed, there is a conflict on `venue.vue`.

**Comment by marimeireles** [comment]
@SylvainCorlay just fixed it.

**Pull request merged**
